// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: api/repertory/v1/repertory.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepertoryService_Purchase_FullMethodName      = "/repertory.v1.RepertoryService/Purchase"
	RepertoryService_AddGoods_FullMethodName      = "/repertory.v1.RepertoryService/AddGoods"
	RepertoryService_FindRepertory_FullMethodName = "/repertory.v1.RepertoryService/FindRepertory"
)

// RepertoryServiceClient is the client API for RepertoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepertoryServiceClient interface {
	Purchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseReply, error)
	AddGoods(ctx context.Context, in *AddRepertoryRequest, opts ...grpc.CallOption) (*AddRepertoryReply, error)
	FindRepertory(ctx context.Context, in *FindRepertoryRequest, opts ...grpc.CallOption) (*FindRepertoryReply, error)
}

type repertoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepertoryServiceClient(cc grpc.ClientConnInterface) RepertoryServiceClient {
	return &repertoryServiceClient{cc}
}

func (c *repertoryServiceClient) Purchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseReply)
	err := c.cc.Invoke(ctx, RepertoryService_Purchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repertoryServiceClient) AddGoods(ctx context.Context, in *AddRepertoryRequest, opts ...grpc.CallOption) (*AddRepertoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRepertoryReply)
	err := c.cc.Invoke(ctx, RepertoryService_AddGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repertoryServiceClient) FindRepertory(ctx context.Context, in *FindRepertoryRequest, opts ...grpc.CallOption) (*FindRepertoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRepertoryReply)
	err := c.cc.Invoke(ctx, RepertoryService_FindRepertory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepertoryServiceServer is the server API for RepertoryService service.
// All implementations must embed UnimplementedRepertoryServiceServer
// for forward compatibility.
type RepertoryServiceServer interface {
	Purchase(context.Context, *PurchaseRequest) (*PurchaseReply, error)
	AddGoods(context.Context, *AddRepertoryRequest) (*AddRepertoryReply, error)
	FindRepertory(context.Context, *FindRepertoryRequest) (*FindRepertoryReply, error)
	mustEmbedUnimplementedRepertoryServiceServer()
}

// UnimplementedRepertoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepertoryServiceServer struct{}

func (UnimplementedRepertoryServiceServer) Purchase(context.Context, *PurchaseRequest) (*PurchaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Purchase not implemented")
}
func (UnimplementedRepertoryServiceServer) AddGoods(context.Context, *AddRepertoryRequest) (*AddRepertoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGoods not implemented")
}
func (UnimplementedRepertoryServiceServer) FindRepertory(context.Context, *FindRepertoryRequest) (*FindRepertoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRepertory not implemented")
}
func (UnimplementedRepertoryServiceServer) mustEmbedUnimplementedRepertoryServiceServer() {}
func (UnimplementedRepertoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeRepertoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepertoryServiceServer will
// result in compilation errors.
type UnsafeRepertoryServiceServer interface {
	mustEmbedUnimplementedRepertoryServiceServer()
}

func RegisterRepertoryServiceServer(s grpc.ServiceRegistrar, srv RepertoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRepertoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepertoryService_ServiceDesc, srv)
}

func _RepertoryService_Purchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepertoryServiceServer).Purchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepertoryService_Purchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepertoryServiceServer).Purchase(ctx, req.(*PurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepertoryService_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRepertoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepertoryServiceServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepertoryService_AddGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepertoryServiceServer).AddGoods(ctx, req.(*AddRepertoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepertoryService_FindRepertory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRepertoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepertoryServiceServer).FindRepertory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepertoryService_FindRepertory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepertoryServiceServer).FindRepertory(ctx, req.(*FindRepertoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepertoryService_ServiceDesc is the grpc.ServiceDesc for RepertoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepertoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repertory.v1.RepertoryService",
	HandlerType: (*RepertoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Purchase",
			Handler:    _RepertoryService_Purchase_Handler,
		},
		{
			MethodName: "AddGoods",
			Handler:    _RepertoryService_AddGoods_Handler,
		},
		{
			MethodName: "FindRepertory",
			Handler:    _RepertoryService_FindRepertory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/repertory/v1/repertory.proto",
}
