// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: api/gateway/v1/gateway.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuGoosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GoodsId       uint32                 `protobuf:"varint,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuGoosRequest) Reset() {
	*x = BuGoosRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuGoosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuGoosRequest) ProtoMessage() {}

func (x *BuGoosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuGoosRequest.ProtoReflect.Descriptor instead.
func (*BuGoosRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *BuGoosRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BuGoosRequest) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BuGoosRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BuGoosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuGoosReply) Reset() {
	*x = BuGoosReply{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuGoosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuGoosReply) ProtoMessage() {}

func (x *BuGoosReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuGoosReply.ProtoReflect.Descriptor instead.
func (*BuGoosReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *BuGoosReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_api_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1capi/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\x1a\x1cgoogle/api/annotations.proto\"_\n" +
	"\rBuGoosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\rR\agoodsId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\"'\n" +
	"\vBuGoosReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Z\n" +
	"\aGateway\x12O\n" +
	"\bBuyGoods\x12\x19.gateway.v1.BuGoosRequest\x1a\x17.gateway.v1.BuGoosReply\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/buyB\x13Z\x11api/gateway/v1;v1b\x06proto3"

var (
	file_api_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_api_gateway_v1_gateway_proto_rawDescData []byte
)

func file_api_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_api_gateway_v1_gateway_proto_rawDescData
}

var file_api_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_gateway_v1_gateway_proto_goTypes = []any{
	(*BuGoosRequest)(nil), // 0: gateway.v1.BuGoosRequest
	(*BuGoosReply)(nil),   // 1: gateway.v1.BuGoosReply
}
var file_api_gateway_v1_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.v1.Gateway.BuyGoods:input_type -> gateway.v1.BuGoosRequest
	1, // 1: gateway.v1.Gateway.BuyGoods:output_type -> gateway.v1.BuGoosReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_gateway_proto_init() }
func file_api_gateway_v1_gateway_proto_init() {
	if File_api_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_gateway_proto = out.File
	file_api_gateway_v1_gateway_proto_goTypes = nil
	file_api_gateway_v1_gateway_proto_depIdxs = nil
}
