// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: api/order/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GoodId        uint32                 `protobuf:"varint,3,opt,name=good_id,json=goodId,proto3" json:"good_id,omitempty"`
	GoodQuantity  uint32                 `protobuf:"varint,4,opt,name=good_quantity,json=goodQuantity,proto3" json:"good_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetGoodId() uint32 {
	if x != nil {
		return x.GoodId
	}
	return 0
}

func (x *Order) GetGoodQuantity() uint32 {
	if x != nil {
		return x.GoodQuantity
	}
	return 0
}

type AddOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GoodId        uint32                 `protobuf:"varint,2,opt,name=good_id,json=goodId,proto3" json:"good_id,omitempty"`
	GoodQuantity  uint32                 `protobuf:"varint,3,opt,name=good_quantity,json=goodQuantity,proto3" json:"good_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrderRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddOrderRequest) GetGoodId() uint32 {
	if x != nil {
		return x.GoodId
	}
	return 0
}

func (x *AddOrderRequest) GetGoodQuantity() uint32 {
	if x != nil {
		return x.GoodQuantity
	}
	return 0
}

type AddOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderReply) Reset() {
	*x = AddOrderReply{}
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReply) ProtoMessage() {}

func (x *AddOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReply.ProtoReflect.Descriptor instead.
func (*AddOrderReply) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *AddOrderReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FindOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOrderRequest) Reset() {
	*x = FindOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderRequest) ProtoMessage() {}

func (x *FindOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderRequest.ProtoReflect.Descriptor instead.
func (*FindOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *FindOrderRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOrderReply) Reset() {
	*x = FindOrderReply{}
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderReply) ProtoMessage() {}

func (x *FindOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderReply.ProtoReflect.Descriptor instead.
func (*FindOrderReply) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *FindOrderReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FindOrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_api_order_v1_order_proto protoreflect.FileDescriptor

const file_api_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x18api/order/v1/order.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\"n\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x17\n" +
	"\agood_id\x18\x03 \x01(\rR\x06goodId\x12#\n" +
	"\rgood_quantity\x18\x04 \x01(\rR\fgoodQuantity\"h\n" +
	"\x0fAddOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\agood_id\x18\x02 \x01(\rR\x06goodId\x12#\n" +
	"\rgood_quantity\x18\x03 \x01(\rR\fgoodQuantity\")\n" +
	"\rAddOrderReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\"\n" +
	"\x10FindOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"Q\n" +
	"\x0eFindOrderReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x05order\x18\x02 \x01(\v2\x0f.order.v1.OrderR\x05order2\xbd\x01\n" +
	"\fOrderService\x12U\n" +
	"\bAddOrder\x12\x19.order.v1.AddOrderRequest\x1a\x17.order.v1.AddOrderReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/order/add\x12V\n" +
	"\tFindOrder\x12\x1a.order.v1.FindOrderRequest\x1a\x18.order.v1.FindOrderReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/order/{id}B\x11Z\x0fapi/order/v1;v1b\x06proto3"

var (
	file_api_order_v1_order_proto_rawDescOnce sync.Once
	file_api_order_v1_order_proto_rawDescData []byte
)

func file_api_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)))
	})
	return file_api_order_v1_order_proto_rawDescData
}

var file_api_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_order_v1_order_proto_goTypes = []any{
	(*Order)(nil),            // 0: order.v1.Order
	(*AddOrderRequest)(nil),  // 1: order.v1.AddOrderRequest
	(*AddOrderReply)(nil),    // 2: order.v1.AddOrderReply
	(*FindOrderRequest)(nil), // 3: order.v1.FindOrderRequest
	(*FindOrderReply)(nil),   // 4: order.v1.FindOrderReply
}
var file_api_order_v1_order_proto_depIdxs = []int32{
	0, // 0: order.v1.FindOrderReply.order:type_name -> order.v1.Order
	1, // 1: order.v1.OrderService.AddOrder:input_type -> order.v1.AddOrderRequest
	3, // 2: order.v1.OrderService.FindOrder:input_type -> order.v1.FindOrderRequest
	2, // 3: order.v1.OrderService.AddOrder:output_type -> order.v1.AddOrderReply
	4, // 4: order.v1.OrderService.FindOrder:output_type -> order.v1.FindOrderReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_order_v1_order_proto_init() }
func file_api_order_v1_order_proto_init() {
	if File_api_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_order_v1_order_proto_depIdxs,
		MessageInfos:      file_api_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_order_v1_order_proto = out.File
	file_api_order_v1_order_proto_goTypes = nil
	file_api_order_v1_order_proto_depIdxs = nil
}
